# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build:
    env:
      platform: aws
      region: us-east-1
      account: 1234586887
      username: ${{secrets.USERNAME}}
      password: ${{secrets.PASSWORD}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Display Message"
        run: echo "Hola mundo"

      - name: "Mostrando variables de entorno :)"
        run: |
          echo "Esto es el valor de Platform ${{env.platform}}"
          echo "Este es el valor de Region: ${{env.region}}"
          echo "Este es el valor de Account: ${{env.account}}"

          echo "Este es el valor del username ${{env.username}}"
          echo "Este el valor de password: ${{env.password}}"
    
      - name: "Mostrando variables por defecto"
        run: |
          echo "Evento: ${{toJSON(github.event)}}"

      - name: "Mostrando variables de entorno por defecto :)"
        run: |
          echo "GITHUB_ACTOR: $GITHUB_ACTOR	"
          echo "GITHUB_REPOSITORY $GITHUB_REPOSITORY"
      - name: "Mostrando valores solo si el usuario es correcto :)"
        if: ${{env.username == 'mzrt' && env.password != ''}}
        run: |
          echo "Si existe el usuario :)"
           